language: php

php:
  - 5.3

env:
  - MODULE=Application
  - MODULE=AlbumRest

before_script:
 - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 - composer install

services: mongodb

script: phpunit --configuration module/$MODULE/test/
