language: php

php:
  - 5.3

before_script:
 - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 - composer install

services: mongodb

script: phpunit --bootstrap module/Application/test/Bootstrap.php 
script: phpunit --bootstrap module/AlbumRest/test/Bootstrap.php 